[package]
name = "regop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive"] }
console = "0.15.10"
regex = "1.11.1"
similar = { version = "2.7.0", features = ["inline"] }
